from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    AGENT_SIMULATION_NOT_CONFIGURED = "AGENT_SIMULATION_NOT_CONFIGURED"
    AGENT_SIMULATION_UNAUTHORIZED = "AGENT_SIMULATION_UNAUTHORIZED"

    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
    CUSTOMER_PHONE_ALREADY_EXISTS = "CUSTOMER_PHONE_ALREADY_EXISTS"
    CUSTOMER_DUPLICATE_CANDIDATE_FOUND = "CUSTOMER_DUPLICATE_CANDIDATE_FOUND"

    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_SKU_ALREADY_EXISTS = "PRODUCT_SKU_ALREADY_EXISTS"
    PRODUCT_INVALID_PRICE = "PRODUCT_INVALID_PRICE"

    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_STATUS_NOT_FOUND = "ORDER_STATUS_NOT_FOUND"
    ORDER_ALREADY_FINALIZED = "ORDER_ALREADY_FINALIZED"
    ORDER_INVALID_ITEMS = "ORDER_INVALID_ITEMS"
    ORDER_INVALID_QUANTITY = "ORDER_INVALID_QUANTITY"
    ORDER_INVALID_PRICE = "ORDER_INVALID_PRICE"
    ORDER_ADDRESS_NOT_FOUND = "ORDER_ADDRESS_NOT_FOUND"
    ORDER_ADDRESS_NOT_BELONG_TO_CUSTOMER = "ORDER_ADDRESS_NOT_BELONG_TO_CUSTOMER"
    ORDER_PRODUCT_NOT_FOUND = "ORDER_PRODUCT_NOT_FOUND"
    ORDER_PRODUCT_INACTIVE = "ORDER_PRODUCT_INACTIVE"
    DELIVERY_ROUTE_NOT_FOUND = "DELIVERY_ROUTE_NOT_FOUND"

    VALIDATION_ERROR = "VALIDATION_ERROR"
    BUSINESS_RULE_ERROR = "BUSINESS_RULE_ERROR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class ApiError(Exception):
    def __init__(
        self,
        *,
        status_code: int,
        code: ErrorCode,
        message: str,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.code = code
        self.message = message
        self.details = details or {}
